### ISSUE TITLE
Mapping issue: Wires missing just outside gravity generator

### ISSUE THREAD

**Issue by AnonymousHybi** [Tk420634/Para-Arf#118]
Wires are quite literally missing from the hallway outside the gravity generator. Every round someone will have to reconnect the power cables to the power the grid from what I see.

**Comment by TalkingCactus** [comment]
That's a cable line which you can continue upwards to connect the gravity generator if it runs out of power. With our round length now, we should map it to be completely connected or for it to have more power.

**Comment by thingpony** [comment]
Fixed.
