### ISSUE TITLE
Kahlua bottles have no sprite

### ISSUE THREAD

**Issue by TrueDARK** [Tk420634/Para-Arf#166]
**Problem Description**:
What is the problem? The bottle lacks a sprite

**What did you expect to happen**: 
Why do you think this is a bug? Because it should have one

**What happened instead**:
How is what happened different from what you expected? ITS INVISIBLE

**Why is this bad/What are the consequences:**
Why do you think this is an important issue? AHHHHHH

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue. SPAWN THE BOTTLE

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. I WAS A BARTENDER AND GOT SAD

**Comment by DameonOwen** [comment]
Problem identified. Sprite is named khaluabottle, not kahluabottle.

**Comment by Tk420634** [comment]
Figgsed.
