### ISSUE TITLE
Deathclaw can't language

### ISSUE THREAD

**Issue by thingpony** [Tk420634/Para-Arf#170]
Deathclaws can't use any language but the default languages. .

**Comment by Vulpias** [comment]
Will look over it when I get home.

**Comment by DameonOwen** [comment]
This is still unresolved. Can someone go into a little more detail about what exactly is broken?

**Comment by thingpony** [comment]
The Deathclaw race can't use any other language other than the generic ones.  The character selector lets them select them, but once in-game it doesn't list on their default language's at all.

**Comment by thingpony** [comment]
Seems fixed!
