### ISSUE TITLE
New Map Issues

### ISSUE THREAD

**Issue by DameonOwen** [Tk420634/Para-Arf#182]
Issues are as follows:
1) Game rooms and construction site APCs not connected to power grid.
2) Vault also not connected to the power grid.
3) Upper hallway by the coffee shop lacks air alarms, vents, scubbers, and pipes entirely
4) Cargo, the warehouse, and cargo mining dock also lack air systems, pipes, etc.
5) Xenobiology is lacking an air system as well, though usually its system vents into space.
6) Engineering missing proper consoles for monitoring (e.g. Alert Consoles, Atmos Alert Consoles, Engineering Camera Console, Atmospheric Remote Control console)
7) No heater in chemistry
8) No Library (fill in one of the empty spaces?)

**Comment by DameonOwen** [comment]
9) Most of the airlocks are missing airlock controllers.

**Comment by DameonOwen** [comment]
10) EVA exterior airlock buttons are not pressable from outside. Once you're out, you're out.

**Comment by TalkingCactus** [comment]
Working on this right now, thank you for the list! 😃 


> EVA exterior airlock buttons are not pressable from outside. Once you're out, you're out.

The buttons are located on the same turf as the doors, this means you need to stand adjacent to the door  from either the inside or outside to press them.

**Comment by TalkingCactus** [comment]
Will update this comment as I complete them.
- [x] 1) Game rooms and construction site APCs not connected to power grid.
- [x] 2) Vault also not connected to the power grid.
- [ ] 3) Upper hallway by the coffee shop lacks air alarms, vents, scubbers, and pipes entirely
- [ ] 4) Cargo, the warehouse, and cargo mining dock also lack air systems, pipes, etc.
- [ ] 5) Xenobiology is lacking an air system as well, though usually its system vents into space.
- [ ] 6) Engineering missing proper consoles for monitoring (e.g. Alert Consoles, Atmos Alert Consoles, Engineering Camera Console, Atmospheric Remote Control console)
- [x] 7) No heater in chemistry
- [ ] 8) ../fifty stacks of metals are not accepted into the mech fabricator
- [ ] 9) Arrivals shuttle airlock is now powered and will close on its own

**Comment by thingpony** [comment]
Adding a few more
- Xenobiology kill chamber doesn't kill slimes
- Apparently the mech fab doesn't work? I think it doesn't print parts, but no one didn't explain this.
