### ISSUE TITLE
Bridge officer issue

### ISSUE THREAD

**Issue by Killbow** [Tk420634/Para-Arf#188]
**Problem Description**:
bridge officer has no accesso to the bridge

**What did you expect to happen**: 
to be able to open the door and work!

**What happened instead**:
no access, red blip, gg

**Why is this bad/What are the consequences:**
because it blocks one entire job.

**Steps to reproduce the problem**:
pick bridge officer, go to the door, click

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:No

**Comment by DameonOwen** [comment]
The bridge door has the requirement of captain access (20), but not bridge access (19), which is what the bridge officer has.
