### ISSUE TITLE
Halobages display NT security.

### ISSUE THREAD

**Issue by lukevale** [Tk420634/Para-Arf#190]
**Problem Description**:
When you scan your ID on a halo badge, and activate it it'll display you as being "NT security".

**What did you expect to happen**: 
because ARFS is part of ARF who if i remember the lore correctly left NT

**What happened instead**:
It to say ARF security.

**Why is this bad/What are the consequences:**
Just lore reasons, no game play aspect.

**Steps to reproduce the problem**:
Swipe your ID on a halo card, and activate it.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by DameonOwen** [comment]
Fixed in #194
