### ISSUE TITLE
More map errors!

### ISSUE THREAD

**Issue by thingpony** [Tk420634/Para-Arf#191]
- No salt and pepper shaker in the kitchen
- Random eletrified grilles in maint?
- Science could use a toolbet.
- ORM is backwords so science has to break into mining to get sheets.

**Comment by DameonOwen** [comment]
Additionally - 
Engineering Station monitoring console is the /all variant, which shows burglar and motion alarms. 
Engineering still missing the Engineering Camera Monitor (the one that shows cameras in areas with active alarms)

**Comment by DameonOwen** [comment]
Addendum- 
Dorms are not protected from radiation storms.

**Comment by thingpony** [comment]
Fixed, apart from the alarm console (No idea how to fix it)
