### ISSUE TITLE
Shark Race Markings - Minor

### ISSUE THREAD

**Issue by AlphaM01** [Tk420634/Para-Arf#20]
https://image.prntscr.com/image/anOOGsMBR6iclXgfutnNNg.png
Body markings for sharks are not colourable.
I've checked for a few other races and they all seemed to be working correctly.

**Comment by DameonOwen** [comment]
Bumping, as this still remains an issue. I'll look into it this weekend.

**Comment by DameonOwen** [comment]
Solved in #193
