### ISSUE TITLE
Map Issues: Medical + "Bug" with Chemistry Dispenser

### ISSUE THREAD

**Issue by voltkage** [Tk420634/Para-Arf#207]
**Problem Description**:
What is the problem?
Medical is lacking in a number of important facilities and has a number of small issues throughout.
- The medical wardrobe near the entrence to the medical bay is stuffed so full of clothes there isn't enough space when you close it again.
- The exam room lacks O2 F.A.K.s
- There is no Pysch Office, Emergency Responder Room, Medical Supplies room (should have EVA suits, bio containment gear, and medical syringe gun), and genetics lab.
- Chemistry doesn't contain a stock solution locker or a source for welding fuel aka a dispenser.
- When a beaker is ejected from a machine in the chemistry room it does not appear above the machine so that it can be picked up easily.
- Medical is stocked only with 0- blood and lacks any empty blood bags to get some from blood donors.
- The entirety of tools for surgery are located inside a single bag that can be easily stolen.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
For medical to operate it requires a majority of what is listed above and without it could be a pain to effectively ensure the station remains operational.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
For the chemistry beaker issue

- Place beaker inside either the chem dispenser or the ChemMaster 3k
- Press Eject inside the interface
- Observe that the beaker does not appear over the machine and cannot be picked up without right clicking.

**Comment by thingpony** [comment]
- [ ] Pysch Office

- [ ] Emergency Responder Room

- [ ] Medical Supplies Room

- [ ] Blood packs

- [ ] Smart fridge for chemistry and welding fuel dispensor
 
As for the other stuff, the surgery tools being in a bag is fine. Tools are easily stolen anyway, bag or not. Genetics, we don't really need, if there is a need for genetics science can build them. I'm not aware of what O2 F.A.K.'s are, and the beaker issue is a code issue that I personally don't know how to fix.
