### ISSUE TITLE
Power Delivery - Minor

### ISSUE THREAD

**Issue by DameonOwen** [Tk420634/Para-Arf#21]
**Problem Description**:
The Gravity Generator SMES and AI satellite are not connected to station power as an input

**What did you expect to happen**: 
Them to be connected to station power as an input

**What happened instead**:
They have what they start with in the SMES, and that's it for the round.

**Why is this bad/What are the consequences:**
After a few hours, gravity is lost, and the AI will be lost if power is not restored.

**Steps to reproduce the problem**:
Run a round for 8 hours. It'll happen.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
The round ran for 8 hours. Which tends to happen overnight. In the mean time, random events did a lot of damage, and nothing could be done because there was no gravity.

**Comment by AnonymousHybi** [comment]
Closed cause we dont have 8 hour rounds anymore :v
