### ISSUE TITLE
Missing Sprites: New Mining Weapons

### ISSUE THREAD

**Issue by Drakyle-The-Forgotten-Deity** [Tk420634/Para-Arf#47]
**Problem Description**:
So far found that the Zweihander and Warhammer mining weapons don't have a visible sprite, this likely holds true for all the new weapons introduced to the mining rewards vendor.

(for reference these are the new weapons last I checked:

Short Sword, Gladius, Long Sword, Zweihander, War Hammer, Mace, Halberd, Spear, Rapier, Buckler

**What did you expect to happen**: 

Expected a visible sprite. 

Why do you think this is a bug?

Because why would they have no sprites...they are weapons.

**What happened instead**:

Found no visible sprite.

How is what happened different from what you expected?

Polar opposites, I expected visible, I got invisible.

**Why is this bad/What are the consequences:**

Why is it bad? it's a minor issue but it is difficult to find such weapons with no sprite if you drop them and lose track of where for any reason or are dragged away from them.

Why do you think this is an important issue?

Not exactly important but still at some point should be amended.

**Steps to reproduce the problem**:

Step 1: Get Mining Points.

Step 2: Buy any one of the listed weapons, so far tested on War Hammer and Zweihander

Step 3: right click or alt click the vendor to spot the bought item has been dispensed without a sprite rendering it invisible even when worn. 

The most important section. Review everything you did leading up to causing the issue.

I went mining, I came back, I smelted my ores, I got my points, I bought the weapons, they had no sprites.

**Possibly related stuff (which gamemode was it? What were you doing at the time? 
I doubt the gamemode had anything to do with it but Extended.

Was anything else out of the ordinary happening?)**: I never did find the new mining mobs but that is it's own thing entirely.

Anything else you can tell us:

Yes, I was sent here by Cactus, they are much nerd : P.

**Comment by Tk420634** [comment]
👌
