### ISSUE TITLE
Mining Station Operating Room Unpowered

### ISSUE THREAD

**Issue by DameonOwen** [Tk420634/Para-Arf#51]
**Problem Description**:
Mining Station operating room is not powered.

**What did you expect to happen**: 
Power

**What happened instead**:
No power

**Why is this bad/What are the consequences:**
The room is more useless, and the OR computer can't be used.

**Steps to reproduce the problem**:
Look at the mining station

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: May not be zoned as part of the mining station medbay.

**Comment by Tk420634** [comment]
Fixed in new map uptoot.
