### ISSUE TITLE
Disposals Mismapped

### ISSUE THREAD

**Issue by DameonOwen** [Tk420634/Para-Arf#53]
**Problem Description**:
Garbage from disposals shoots out of the pet store disposal bin.

**What did you expect to happen**: 
It's supposed to shoot out onto the conveyor in Cargo

**What happened instead**:
It flew out of the bin in the new pet store.

**Why is this bad/What are the consequences:**
Recycling isn't done. Items aren't destroyed.

**Steps to reproduce the problem**:
Throw something away. Some of it, if not all, will lead to the pet store. At least, from R&D.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
TK did the mapping.

**Comment by Tk420634** [comment]
Figsed it :fox_face: :dagger:
