### ISSUE TITLE
Taurs no worky

### ISSUE THREAD

**Issue by Tk420634** [Tk420634/Para-Arf#65]
**Problem Description**:
Players can't pick taurs!

**What did you expect to happen**: 
For them to be able to make taurs!

**What happened instead**:
Only admins can!

**Why is this bad/What are the consequences:**
Players can't play Taurs!

**Steps to reproduce the problem**:
Be a non admin, try to make a taur!

**Comment by AnonymousHybi** [comment]
issue priority number 1

**Comment by AnonymousHybi** [comment]
retard squad on it's way to solve issue
