### ISSUE TITLE
Mouse Ears

### ISSUE THREAD

**Issue by TheLightorTheDark** [Tk420634/Para-Arf#66]
**Problem Description**:
What is the problem?
The mouse sprite doesn't have ears, but does have a tail.

**What did you expect to happen**: 
Why do you think this is a bug?
They have no ears, they can't hear.

**What happened instead**:
How is what happened different from what you expected?
They're supposed to have big ears, but instead do not.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
They have a lack of ears, and so I need to use the cat ears/tail instead.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Select Mouse as species, scream.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Fix plox

**Comment by Tk420634** [comment]
Fixed in next pr.
