### ISSUE TITLE
Underwear/Undershirts/Socks for Mouse (at the least)

### ISSUE THREAD

**Issue by TheLightorTheDark** [Tk420634/Para-Arf#67]
**Problem Description**:
What is the problem?
Mice, at the least, can't access Underwear/Undershirts/Socks

**What did you expect to happen**: 
Why do you think this is a bug?
Other species can, why not the squeakers?

**What happened instead**:
How is what happened different from what you expected?
I wanted to have an undershirt, I found there to be none available.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
My mice should be able to wear underclothes, and this may be the case for a handful of other species.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Attempt to give Underwear/Undershirt/Socks, see that Undershirt and Socks are unclickable, and Underwear only gives the selection of 'Nude'.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Fix plox

**Comment by Tk420634** [comment]
Fixed in next PR.
