### ISSUE TITLE
Brig Physicians access broken

### ISSUE THREAD

**Issue by thingpony** [Tk420634/Para-Arf#74]
Brig Physicians, despite it being in their name and being part of security, do not have brig access.

**Comment by TrueDARK** [comment]
Took a look at the access on a guest pass terminal. They have the exact same access as a Medical Doctor as far as I can tell.

**Comment by cebutris** [comment]
Is this still an issue?

**Comment by Tk420634** [comment]
I merged your PR fixing it. I assume you tested it.  So I assume its not.

**Comment by cebutris** [comment]
YES. HAHA. TESTING. THAT IS SOMETHING THAT I DEFINITLEY DID, DO NOT WORRY.

I literally just copied Hibou's PR after you closed it because I changed the access on an entirely different job. I didn't test it, but there's no reason it _shouldn't_ work. Probably isn't an issue anymore.

**Comment by Tk420634** [comment]
:| Can you test it real quick?  It's already been added in.

**Comment by cebutris** [comment]
I can't test it until tonight, sorry

**Comment by Tk420634** [comment]
🍉

**Comment by cebutris** [comment]
I MEAN YOU CAN JUST TEST IT ON THE SERVER? IT'S A TINY CHANGE

**Comment by Tk420634** [comment]
🍉 ❓

**Comment by cebutris** [comment]
NO, HECK OFF

**Comment by Tk420634** [comment]
😿

**Comment by cebutris** [comment]
Don't make me get my gun emoji

**Comment by Tk420634** [comment]
I'll test it, but gotta download resources.  So that's gonna take me like.  An hour.

**Comment by Tk420634** [comment]
Jess got it, we gucci.
