### ISSUE TITLE
Dionae

### ISSUE THREAD

**Issue by El-Fishii** [Tk420634/Para-Arf#79]
**Problem Description**:
What is the problem?
For a Species that doesn't need to breath, they still "smell rot" and are mini-stunned by throwing up.
**What did you expect to happen**: 
Why do you think this is a bug?
As above
**What happened instead**:
How is what happened different from what you expected?
For a species that is a plant. we don't breath.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Being a medic as Dinoae, being stunned during surgery is rather bad.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Dead body near you no mask.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Tk420634** [comment]
Yeeaaaah.  That doesn't really make much sense, tbqh. :|  We'll see what we can do about it, but I really have no idea how to uh... stop that from happening.
