### ISSUE TITLE
NT Shit everywhere like wdf - Minor

### ISSUE THREAD

**Issue by DexterDude** [Tk420634/Para-Arf#80]
**Problem Description**:
Weird ass NT logos everywhere even though ARFS is supposed to be a bunch of furries and a few humans that broke off from NT 🤔 (Also on High(Cent)Com reports the NT logo is stamped)

**What did you expect to happen**: 
There to be ARF logos

**What happened instead**:
There were NT logos

**Why is this bad/What are the consequences:**
Not important, but BREAKS MUH IMMERSION (lmao i say immersion like a bunch of furries and being to breathe PURE O2 makes sense)

**Steps to reproduce the problem**:
Look in Blueshield/ARF rep office

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing

**Comment by TrueDARK** [comment]
Death to NanoTrasen
