### ISSUE TITLE
Holders.dm runtime error

### ISSUE THREAD

**Issue by DameonOwen** [Tk420634/Para-Arf#85]
DEBUG: Runtime in holders.dm,45: Cannot execute null.return air(). [view]
DEBUG: Runtime in holders.dm,45: Cannot execute null.return air(). [view]
DEBUG: Runtime in code/modules/garbage_collection/garbage_collector.dm,185: WARNING: /obj/item/weapon/holder/micro is not returning a qdel hint. It is being placed in the queue. Further instances of this type will also be queued.

[23:09:29] Runtime in holders.dm,45: Cannot execute null.return air().
   Caught by process: mob
   proc name: get turf air (/obj/item/weapon/holder/micro/proc/get_turf_air)
   src: Keliiroh Issehei () (/mob/living/carbon/human/unathi)
   src.loc: Keliiroh Issehei (78,118,1) (/obj/item/weapon/holder/micro)
   src.loc: Dameon Owen (/mob/living/carbon/human)
   call stack:
   Keliiroh Issehei (/obj/item/weapon/holder/micro): get turf air()
   Keliiroh Issehei (/obj/item/weapon/holder/micro): return air()
   Keliiroh Issehei (/mob/living/carbon/human/unathi): Life()
   Keliiroh Issehei (/mob/living/carbon/human/unathi): Life()
   Keliiroh Issehei (/mob/living/carbon/human/unathi): Life()
   mob (/datum/controller/process/mob): doWork()
   mob (/datum/controller/process/mob): process()
   /datum/controller/processSched... (/datum/controller/processScheduler): runProcess(mob (/datum/controller/process/mob))

**Comment by AnonymousHybi** [comment]
Did anything happen? like for example did Kelilroh stop breathing? if so this isn't much of an issue, its just spaghetti code.

**Comment by AnonymousHybi** [comment]
cause that exception's me being a cheeky shit trying to make it so you guys can breathe and its not the best code

**Comment by DameonOwen** [comment]
I don't think it caused anything weird. It was just spamming because I happen to have runtime errors show on my client.

**Comment by AnonymousHybi** [comment]
Ah, just turn off debug logs then :v You're not really debugging anything. I can't really be assed fixing something which already works. (pulling a Tk here)
