### ISSUE TITLE
Probably Broken Autopsy Scanners

### ISSUE THREAD

**Issue by TrueDARK** [Tk420634/Para-Arf#95]
What is the problem?
Autopsy scanners don't print reports.

Why do you think this is a bug?
Expected to have a printed report of an injury on a dead thing.

How is what happened different from what you expected?
I cried and hugged my mommy because either I couldn't figure it out or it was broken.

Why do you think this is an important issue?
You wont be able to figure out how shit dies.

The most important section. Review everything you did leading up to causing the issue.
Scan a dead bitch. And just try to find a print button. You wont.

Anything else you can tell us.
Cebu is cute

**Comment by thingpony** [comment]
You just click on the dead body in question, then click on the scanner. It prints off a piece of paper in your empty hand.
